// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjenBK6MNTCgXgXgmzgfKZ_qqXRMNAPw',
    appId: '1:312576336309:web:29d14c5174a7fa4576b9fc',
    messagingSenderId: '312576336309',
    projectId: 'bo-family',
    authDomain: 'bo-family.firebaseapp.com',
    storageBucket: 'bo-family.firebasestorage.app',
    measurementId: 'G-TYFJH5W9PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYRITk6zmYYAZGXL_awIWRDLJqaOd9isc',
    appId: '1:312576336309:android:20e07462746a057976b9fc',
    messagingSenderId: '312576336309',
    projectId: 'bo-family',
    storageBucket: 'bo-family.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyQJERHTv_x89LoKlRx1_t6EKzUfs7io',
    appId: '1:312576336309:ios:9a179f40e250649c76b9fc',
    messagingSenderId: '312576336309',
    projectId: 'bo-family',
    storageBucket: 'bo-family.firebasestorage.app',
    iosBundleId: 'com.example.bualainain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjyQJERHTv_x89LoKlRx1_t6EKzUfs7io',
    appId: '1:312576336309:ios:9a179f40e250649c76b9fc',
    messagingSenderId: '312576336309',
    projectId: 'bo-family',
    storageBucket: 'bo-family.firebasestorage.app',
    iosBundleId: 'com.example.bualainain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqjenBK6MNTCgXgXgmzgfKZ_qqXRMNAPw',
    appId: '1:312576336309:web:9db1c1630717227476b9fc',
    messagingSenderId: '312576336309',
    projectId: 'bo-family',
    authDomain: 'bo-family.firebaseapp.com',
    storageBucket: 'bo-family.firebasestorage.app',
    measurementId: 'G-Z4075PXD6K',
  );
}
